scrape_configs:
  # ============================================================================
  # APPLICATION SPRING BOOT RAG
  # ============================================================================
  - job_name: 'spring-boot-rag'
    scheme: https
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['BACKEND_URL_PLACEHOLDER']
        labels:
          application: 'rag-system'
          service: 'transaction-service'
          environment: 'production'
          type: 'spring-boot'
    tls_config:
      insecure_skip_verify: false